#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    # Write your code here
    maximum = max(arr)
    minimum = min(arr)
    total = sum(arr)
    
    max_sum = total - minimum
    min_sum = total - maximum
     
    print(f"{min_sum} {max_sum}")
if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)


# to find sum of max or min value from the array we have to find the min and max elements and then we have to subtract the min and max value from the total value so that we will get the max_sum and min_sum
