#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    positive = negative = zero = 0
    n = len(arr)
    for i in range(0,n):
        if(arr[i] > 0):
            positive += 1
        elif(arr[i] < 0):
            negative += 1
        else:
            zero += 1
    pos_ratio = positive / n
    neg_ratio = negative / n
    zero_ratio = zero / n
    
    print(f"{pos_ratio: .6f}")
    print(f"{neg_ratio: .6f}")
    print(f"{zero_ratio: .6f}")
    

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
